MODEL:
  META_ARCHITECTURE: "ViTDet"
  BACKBONE:
    NAME: "D2ViT"
  VIT:
    NAME: "vit_small_patch8"
    IMAGE_SIZE: 1024
    PATCH_SIZE: 8
    EMBED_DIM: 384
    DEPTH: 12
    NUM_HEADS: 6
    MLP_RATIO: 4.0
    QKV_BIAS: True
    DROP_PATH_RATE: 0.1
    RELATIVE_POSITION_EMBED: True
    WINDOW_BLOCK_INDEXES: [0, 1, 3, 4, 6, 7, 9, 10]
    USE_ACT_CHECKPOINT: False
  FPN:
    IN_FEATURES: ["p1", "p2", "p3", "p4"]
    OUT_CHANNELS: 256
    NORM: "LN"
  ROI_HEADS:
    NUM_CLASSES: 1
INPUT:
  FORMAT: "RGB"
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 5000
DATALOADER:
  NUM_WORKERS: 4
